### ISSUE TITLE
Nuget Package

### ISSUE THREAD

**Issue by Yeah69** [ExRam/ExRam.ReactiveCollections#2]
Is there a nuget package for this project? If not, could you please create one?

A while back, I created a similar project called MuVaViMo (https://github.com/Yeah69/MuVaViMo) and it works well for simple use cases. However, at that time I wasn't into Reactive Extensions and did create the project without it. Since I discovered Rx I thought that Rx would be an improvement, but hadn't managed to spare enough time to refactor and extend my project.
Consindering the description of your project I think that ExRam.ReactiveCollections is far ahead of my project. Hence, I would like to test your project as replacement for MuVaViMo.

**Comment by danielcweber** [comment]
I was planning to put up a NuGet for this long ago, I guess I should.

**Comment by danielcweber** [comment]
A preview-package has been published here: https://www.nuget.org/packages/ExRam.ReactiveCollections/

Feel free to tell me how it works for you.

**Comment by Yeah69** [comment]
Thank you. I made a quick test. The nuget package works. More sophisticated tests will follow. However it may take a while until I give you some feedback, because I'll test it on a hobby project, which I develop in my free time.
